name: My First GitHub Actions Workflow
on: push
jobs:
  great:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Say Hello
        run: echo "Hello from GitHub Actions!" 
      - name: Print Date and Time
        run: date
      - name: Print Branch name
        run: echo "Branch is: ${{ github.ref_name }}"
      - name: List Files in Repo
        run: ls -lrth
      - name: Print OS info
        run: uname -a

              
